- name: "Create user config file directories, if not exist"
  ansible.builtin.file:
    path: "{{ yazi_config_file_path | dirname }}"
    state: directory
  become: true
  become_user: "{{ yazi_user_name }}"

- name: "Configure all Yazi behavior in '{{ yazi_config_file_path }}'"
  ansible.builtin.template:
    dest: "{{ yazi_config_file_path }}"
    src: "yazi_toml.j2"
  become: true
  become_user: "{{ yazi_user_name }}"

